swagger: "2.0"
info:
  version: "1.0.0"
  title: Player API
  description: API for managing players

paths:
  /player/all:
    get:
      summary: Get all players
      description: Retrieve a list of all players
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Player"

  /player/add:
    post:
      summary: Add a new player
      description: Add a new player with the given name
      parameters:
        - name: name
          in: body
          description: Name of the player
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful operation

  /player/delete/{id}:
    delete:
      summary: Delete a player
      description: Delete the player with the given ID
      parameters:
        - name: id
          in: path
          description: ID of the player to delete
          required: true
          type: integer
      responses:
        200:
          description: Successful operation

  /player/update:
    put:
      summary: Update player name
      description: Update the name of a player
      parameters:
        - name: update
          in: body
          description: Player ID and updated name
          required: true
          schema:
            $ref: "#/definitions/UpdateName"
      responses:
        200:
          description: Successful operation

  /game/all:
    get:
      summary: Get all games
      description: Retrieve a list of all games
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Game"

